---
title: "Semana 04"
---


## Slides

{{< fa file-powerpoint size=lg >}} [Flexibilidade: Funções de Base, Polinômios, Splines e Séries](/aulas/semanais/semana_03_funcoes_base_splines_series.html#/title-slide "Funções de Base, Polinômios, Splines e Séries"){aria-label="Funções de Base, Polinômios, Splines e Séries"}

{{< fa file-powerpoint size=lg >}} [Seleção de Variáveis e Regularização](/aulas/semanais/semana_04_selecao_regularizacao_v2.html#/title-slide "Seleção de Variáveis e Regularização"){aria-label="Seleção de Variáveis e Regularização"}


## Material Complementar

{{< fa folder size=lg >}} [Generalização e Regularização](/material_complementar/regularizacao_pratica.html "Material Complementar A1"){aria-label="Material Complementar A1"}


## Atividade Avaliativa - A1

{{< fa list-check size=lg >}} [ A1 — Generalização e Regularização](/atividades/atividade_1_generalizacao_regularizacao.html "Atividade Avaliativa - A1"){aria-label="Atividade Avaliativa - A1"}

::: {.callout-important}
## Informações da atividade

**Valor:** 20 pontos  
**Liberação:** 16/09/2026  
**Entrega:** 27/09/2026  

Entrega via [Moodle](https://moodlepresencial.ufop.br/login/index.php)
:::

