---
title: "Semana 06"
---


## Slides

{{< fa file-powerpoint size=lg >}} [Métodos Locais: KNN, Kernel e Regressão Local](/aulas/semanais/semana_05_metodos_locais_knn_kernel.html#/title-slide "KNN, Kernel e Regressão Local"){aria-label="KNN, Kernel e Regressão Local"}

{{< fa file-powerpoint size=lg >}} [Kernels, RKHS, SVR e SVM](/aulas/semanais/semana_06_kernels_rkhs_svr_svm.html#/title-slide "Kernels, RKHS, SVR e SVM"){aria-label="Kernels, RKHS, SVR e SVM"}


## Material Complementar

{{< fa folder size=lg >}} [Métodos Locais e Kernels](/material_complementar/material_complementar_a2_metodos_locais.html "Material Complementar A2"){aria-label="Material Complementar A2"}


## Atividade Avaliativa - A2

{{< fa list-check size=lg >}} [A2 — Métodos Locais e Kernels](/atividades/atividade_2_metodos_locais_kernels.html "Atividade Avaliativa - A2"){aria-label="Atividade Avaliativa - A2"}

::: {.callout-important}
## Informações da atividade

**Valor:** 20 pontos  
**Liberação:** 30/09/2026  
**Entrega:** 11/10/2026  

Entrega via [Moodle](https://moodlepresencial.ufop.br/login/index.php)
:::

