project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "EST335 - Métodos Estatísticos para Machine Learning"
  description: "Homepage da disciplina EST335 - Métodos Estatísticos para Machine Learning, 2026/1"
  site-url: "http://professortp.com.br/est335/"

  repo-url: "https://github.com/tiagomartin/est335"
  repo-actions: [edit, issue]

  open-graph: true
  
  page-footer:
    right: "Página construída usando [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2026, Tiago Pereira"


  sidebar:
    tools: 
    - icon: github
      text: github
      href: https://github.com/tiagomartin/est335
    background: "#F2F2F2"
    logo: "images/logo.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - aulas.qmd
      #- estudos.qmd
      #- exercicios.qmd
      #- resolucao.qmd
      #- formulario.qmd
      #- analises.qmd
      #- plano.qmd
      - cronograma.qmd
      #- material.qmd
      #- revisao.qmd
      #- notas.qmd
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: false


