---
title: "Cronograma da Disciplina"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
---

Esta página contém um esboço dos tópicos, conteúdos e tarefas para o semestre. Este cronograma será atualizado conforme o semestre avança.

<!-- https://fontawesome.com/search?o=r&m=free -->

<!-- https://jpswalsh.github.io/academicons/ -->

<!-- [{{< fa file-pdf size=2xl >}}](/weeks/week-1.html#prepare){aria-label="Week 1 summary"}  |  [️](/slides/lec-1.html "Lecture slides"){aria-label="Lecture 1 slides"}  |       [{{< fa laptop-file size=2xl >}}](/ae/ae-0-movies.html "Application exercise"){aria-label="Application Exercise 0 instructions"} -->

<!-- {{< fa brands r-project size=2xl >}}  -  scripts -->

<!-- {{< fa file-powerpoint size=2xl >}}   -  slides -->

<!-- {{< fa laptop-file size=2xl >}}  -  estudo de caso -->

<!-- {{< fa file-pdf size=2xl >}}  -  artigo -->

<!-- {{< fa table size=2xl >}}  -  tabelas estatisticas -->

<!-- {{< fa file-lines size=2xl >}}  -  exercicios -->

<!-- {{< fa folder size=2xl >}}  -  material complementar -->

<!-- {{< fa list-check size=2xl >}}  -  projeto -->

::: column-screen-inset-right
| Semana | Data | Tópico | Artigo | Slides | EC | LE | Script | MC | Projeto |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| [1](programacao/semana-1.html) | Seg, 24/08 | Fundamentos do Aprendizado Estatístico |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/semanais/semana_01_fundamentos_aprendizado_supervisionado.html#/title-slide "Fundamentos do Aprendizado Estatístico"){aria-label="Fundamentos do Aprendizado Estatístico"} |  |  |  |  |  |
|  | Qua, 26/08 | Fundamentos do Aprendizado Estatístico |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/semanais/semana_01_fundamentos_aprendizado_supervisionado.html#/title-slide "Fundamentos do Aprendizado Estatístico"){aria-label="Fundamentos do Aprendizado Estatístico"} |  |  |  |  |  |
| [2](programacao/semana-2.html) | Seg, 31/08 | Fundamentos do Aprendizado Estatístico |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/semanais/semana_01_fundamentos_aprendizado_supervisionado.html#/o-modelo-estimado-depende-dos-dados-1 "Fundamentos do Aprendizado Estatístico"){aria-label="Fundamentos do Aprendizado Estatístico"} |  |  |  |  |  |
|  | Qua, 02/09| Modelos Lineares: Regressão e Classificação |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/semanais/semana_02_modelos_lineares_regressao_classificacao.html#/title-slide "Modelos Lineares: Regressão e Classificação"){aria-label="Modelos Lineares: Regressão e Classificação"} |  |  |  |  |  |
| [3](programacao/semana-3.html) | Seg, 07/09 | **Feriado: Independência do Brasil** |  |  |  |  |  |
|  | Qua, 09/09| Funções de Base, Polinômios, Splines e Séries |  | [{{< fa file-powerpoint size=2xl >}}](aulas/semanais/semana_03_funcoes_base_splines_series.html#/title-slide "Funções de Base, Polinômios, Splines e Séries"){aria-label="Funções de Base, Polinômios, Splines e Séries"} |  |  |  |  |  |
:::

```{r echo = FALSE}
knitr::knit_exit()
```


