{
  "hash": "208b9d9f4abb5830456d0163ea5d7e03",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Parte II : Classificação\"\nsubtitle: \"<span class='custom-subtitle'>Outros Aspectos de Classificação</span>\"\nformat: \n  revealjs:\n    width: 1600\n    height: 900\n    footer: \"\"\n    theme: quartomonothemer.scss\n    slide-number: c/t\n    show-slide-number: all\n    preview-links: auto\n    self-contained: false\n    embed-resources: false\n    code-link: true\n    highlight-style: a11y\n    chalkboard: true\n    #incremental: true\n    #transition: slide\n  # beamer:          # Slides em PDF (LaTeX/Beamer)\n  #   aspectratio: 169   # 16:9\n  #   keep-tex: true     # opcional, guarda o .tex gerado\nincremental: false\ncode-link: true\nbibliography: references.bib\ntitle-slide-attributes:\n    data-background-image: /images/back.png\n    data-background-size: cover\n    data-background-opacity: \"0.3\"\nexecute:\n  echo: false\n  warning: false\n  message: false\n  fig-format: png\n  freeze: auto\n  cache: true\n---\n\n\n# Outros Aspectos de Classificação\n\n\n## Classificação: assimetria, desbalanceamento e cortes\n\nNem todo problema de classificação é **simétrico**. Na prática, os erros têm **custos diferentes** e as classes raramente são **balanceadas**.<br><br>\n\n\n### Assimetria na Função de Perda \n\nAté aqui assumimos que `FN` e `FP` têm o mesmo custo (perda 0-1), isto é, a função $\\mathbb{I}(g(\\mathbf{x}) \\neq Y)$ atribui perda 1 para todo erro cometido. Na prática, os custos são diferentes.\n\n**Exemplos:**\n\n- **Diagnóstico de câncer:** `FN` (não diagnosticar) é muito mais grave que `FP`\n- **Detecção de default:** não detectar um calote custa mais que um falso alarme\n\n\n---\n\n### Conjuntos desbalanceados\n\nUm dataset é desbalanceado quando uma classe tem **muito mais** observações que a outra.\n\n- **Exemplos clássicos:** fraude, diagnóstico de doenças raras, inadimplência.\n\n\n\n\n\n\nNa base **Default**, a classe `Yes` representa aproximadamente 3,3% dos dados.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ISLR2)\nprop.table(table(Default$default))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    No    Yes \n0.9667 0.0333 \n```\n\n\n:::\n:::\n\n\n**Problema:** um classificador que chama tudo de `No` tem aproximadamente 97% de acurácia, mas nunca detecta a **classe de interesse**.\n\n---\n\n### Conjuntos desbalanceados\n\n\n\n> **Classe de interesse:** categoria cuja identificação é o principal objetivo do modelo, geralmente representando o evento mais relevante ou raro a ser previsto.\n\n**Métricas adequadas:**\n\n- Sensibilidade (recall), especificidade\n- Curva ROC e AUC\n- F1-score, Precision-Recall\n\n\n\n\n\n## Classificação: assimetria, desbalanceamento e cortes\n\n\n\n\n- Se uma classe é rara, ou seja, $\\mathbb{P}(Y=1\\mid\\mathbf{x}) << 0.5$ para quase todas as observações, então o classificador de Bayes,\n$\\mathbb{I}\\!\\left(\\mathbb{P}(Y=1\\mid\\mathbf{x}) \\geq 0.5\\right)$,passa a prever sempre $g(\\mathbf{x})=0$ (classificador trivial), minimizando a perda $\\mathbb{P}(g(\\mathbf{X}) \\neq Y)$.<br><br>\n  \n  \n- Como os métodos de classificação tendem aproximar o classificador de Bayes, naturalmente irão se aproximar do classificador trivial, neste caso.\n\n\n## Classificação: assimetria, desbalanceamento e cortes\n\n### Três abordagens\n\n1. **Função de risco assimétrica:**\n\n$$R(g) = \\ell_1 P(Y \\neq g(\\mathbf{x}), Y=0) + \\ell_0 P(Y \\neq g(\\mathbf{x}), Y=1)$$\n\n- $\\ell_1$ = custo do Falso Positivo\n- $\\ell_0$ = custo do Falso Negativo\n\n\n## Classificação: assimetria, desbalanceamento e cortes\n\n### Três abordagens\n\n1. **Função de risco assimétrica:**\n\nO classificador de Bayes com perda assimétrica é:\n\n$$g(x) = \\mathbb{I}\\left(P(Y=1|\\mathbf{x}) > \\frac{\\ell_1}{\\ell_0 + \\ell_1}\\right)$$\n\n- Cutoff padrão (0,5) é um **caso particular** quando $\\ell_0 = \\ell_1$\n- Se `FN` custa **9 vezes mais** que `FP` ($\\ell_0 = 9$, $\\ell_1 = 1$) → cutoff ótimo = **0,1**\n- Definir os custos é um problema de **negócio**, não estatístico\n\n## Classificação: assimetria, desbalanceamento e cortes\n\n### Três abordagens\n\n2. **Curva ROC (*Receiver Operating Characteristic*):**\n\n**A Curva ROC permite avaliar o classificador para todos os limiares de decisão**, possibilitando escolher aquele mais adequado aos custos da aplicação.\n\n\n\nRepresenta o compromisso entre\n\n$$\n\\text{TPR}=\\frac{TP}{TP+FN}\n\\qquad\\text{e}\\qquad\n\\text{FPR}=\\frac{FP}{FP+TN}.\n$$\n\nEm vez de utilizar o limiar fixo\n\n$$\n\\mathbb{P}(Y=1\\mid\\mathbf{x})\\ge0.5,\n$$\n\n## Classificação: assimetria, desbalanceamento e cortes\n\n### Três abordagens\n\n2. **Curva ROC (*Receiver Operating Characteristic*):**\n\n\n\nescolhe-se um limiar $\\tau$ (*threshold*), resultando no classificador\n\n$$\ng(\\mathbf{x})=\n\\mathbb{I}\\!\\left(\\mathbb{P}(Y=1\\mid\\mathbf{x})\\ge\\tau\\right).\n$$\n\n\n**Quanto maior o custo do falso negativo, menor tende a ser $\\tau$; quanto maior o custo do falso positivo, maior tende a ser $\\tau$.**\n\n\n\n## Classificação: assimetria, desbalanceamento e cortes\n\n\n::: {layout-ncol=2}\n\n![](/images/classificacao/curva_roc.gif){fig-align=\"center\"}\n\n\n![](/images/classificacao/curva_roc_estatica.png){fig-align=\"center\"}\n:::\n\n---\n\n### Threshold Ótimo pelo Índice de Youden\n\nO Índice de Youden mede a capacidade discriminativa de um classificador para um determinado limiar:\n\n$$\nJ(\\tau)=\\text{Sensibilidade}(\\tau)+\\text{Especificidade}(\\tau)-1.\n$$\n\nO limiar ótimo é aquele que maximiza esse índice:\n\n$$\n\\tau^{*}=\\arg\\max_{\\tau} J(\\tau).\n$$\n\nEquivalentemente,\n\n$$\n\\tau^{*}=\\arg\\max_{\\tau}\n\\left[\n\\text{TPR}(\\tau)-\\text{FPR}(\\tau)\n\\right].\n$$\n\n\n\n## Classificação: assimetria, desbalanceamento e cortes\n\n### Três abordagens\n\n3. **Super-sampling** e **Sub-sampling**\n\n\n- Alterar **artificialmente** a prevalência de cada categoria na amostra de treinamento\n- *Super-sampling*: replicar observações da classe minoritária\n- *Sub-sampling*: remover observações da classe majoritária\n\n\n--- \n\n![](/images/classificacao/sub_super_sampling.png){fig-align=\"center\"}\n\n## Classificação: assimetria, desbalanceamento e cortes\n\n<br>\n\n> ⚠️ **Ponto central:** A fonte do problema **não é o desbalanceamento em si**, mas sim os **custos de classificação serem diferentes**. O classificador de Bayes padrão minimiza apenas a probabilidade de erro,ignorando custos assimétricos entre `FN` e `FP`.\n\n\n\n\n## Dataset Shift e Viés de Seleção\n\n**Contexto:** quando os dados de **treino** e **teste** vêm de distribuições diferentes, as premissas do aprendizado de máquina são violadas e o modelo degrada.<br><br>\n\n### Tipos de dataset shift\n\n**1. Covariate Shift**\n\nA distribuição das **variáveis preditoras** muda, mas a relação $P(Y|\\mathbf{x})$ permanece a mesma:\n\n$$\nP_{\\text{treino}}(\\mathbf{x}) \\neq P_{\\text{teste}}(\\mathbf{x}) \\quad \\text{e} \\quad P_{\\text{treino}}(Y|\\mathbf{x}) = P_{\\text{teste}}(Y|\\mathbf{x})\n$$\n\n- **Exemplo:** modelo treinado com clientes de SP, aplicado em clientes do RJ\n\n\n---\n\n\n\n- **Solução:** **ponderar** as observações por $$\\beta(\\mathbf{x}) = \\frac{P_{\\text{teste}}(\\mathbf{x})}{P_{\\text{treino}}(\\mathbf{x})}$$\n\n\n![](/images/classificacao/covariate_shift.png){fig-align=\"center\"}\n\n\n---\n\n**2. Prior Shift**\n\nA distribuição da **variável resposta** muda:\n\n$$\nP_{\\text{treino}}(Y) \\neq P_{\\text{teste}}(Y) \\quad \\text{e} \\quad P_{\\text{treino}}(\\mathbf{x}|Y) = P_{\\text{teste}}(\\mathbf{x}|Y)\n$$\n\n- **Exemplo:** detector de spam treinado com 50%/50% de spams/hams, aplicado em proporção real 5%/95%\n\n\n---\n\n\n- **Solução:** recalibrar as probabilidades usando $$P_{\\text{teste}}(Y)$$\n\n\n\n**3. Viés de Seleção (Selection Bias)**\n\nA amostra de treino não é representativa da população por causa de **como os dados foram coletados**.\n\n- **Exemplo:** modelo de risco de crédito treinado apenas com clientes que já foram aprovados em financiamentos anteriores (os rejeitados não aparecem nos dados)\n\n- **Mais difícil de corrigir**, requer dados adicionais ou modelagem do mecanismo de seleção\n\n\n## R: Dataset Shift e Viés de Seleção\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exemplo: correcao de Covariate Shift\n# Dados de treino viezados e teste com distribuicao diferente\nset.seed(335)\n\nn_treino <- 500\nn_teste <- 200\n\n# Treino: X ~ N(0, 1); Teste: X ~ N(1.5, 1)\nX_treino <- rnorm(n_treino, 0, 1)\nX_teste  <- rnorm(n_teste, 1.5, 1)\n\n# Fator de correcao beta(x) = P_teste(X) / P_treino(X)\n# Neste caso: beta(x) = dnorm(x, 1.5, 1) / dnorm(x, 0, 1)\npesos <- dnorm(X_treino, 1.5, 1) / dnorm(X_treino, 0, 1)\nsummary(pesos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.0037  0.1113  0.3156  1.1676  0.9503 37.4111 \n```\n\n\n:::\n:::\n\n\n---\n\n### Interpretação\n\nNeste exemplo, os dados de treino e teste são gerados a partir de distribuições diferentes:\n\n- Treino: $\\mathbf{x} \\sim N(0,1)$\n- Teste: $\\mathbf{x} \\sim N(1.5,1)$\n\nAssim, ocorre **Covariate Shift**, pois\n\n$$\nP_{\\text{treino}}(\\mathbf{x})\\neq P_{\\text{teste}}(\\mathbf{x}),\n$$\n\nenquanto a relação entre $\\mathbf{x}$ e $Y$ é assumida constante.\n\n---\n\n\nPara corrigir esse desbalanceamento entre as distribuições, cada observação do conjunto de treino recebe um peso\n\n$$\n\\beta(\\mathbf{x})=\n\\frac{P_{\\text{teste}}(\\mathbf{x})}\n     {P_{\\text{treino}}(\\mathbf{x})}.\n$$\n\n**Interpretação dos pesos obtidos**\n\n- Peso **próximo de 1**: a observação é igualmente representativa nos conjuntos de treino e teste.\n- Peso **menor que 1**: a observação é mais frequente no treino do que no teste e tem sua influência reduzida.\n- Peso **maior que 1**: a observação é rara no treino, mas comum no teste, recebendo maior importância durante o treinamento.\n\n---\n\nNeste exemplo, o peso médio foi **1,17**, porém alguns exemplos receberam pesos muito elevados (máximo **37,41**), indicando regiões do espaço de atributos pouco representadas no treinamento, mas frequentes na distribuição de teste.\n\n\n\n## Combinando Classificadores (Stacking / Blending)\n\n**Ideia central:** em vez de escolher um único modelo, combinar as predições de **múltiplos classificadores base** para obter um desempenho melhor que qualquer um individualmente.\n\n### Arquitetura\n\n- **Nível 0 (base):** $K$ classificadores treinados no dataset original (ex.: logística, árvore, SVM, KNN, etc.)\n- **Nível 1 (meta):** um **meta-classificador** treinado para aprender a ponderar as saídas dos modelos base\n\n**Problema:** se os modelos base forem treinados e suas predições usadas no mesmo dataset, o meta-classificador sofre overfitting.\n\n\n## Combinando Classificadores (Stacking / Blending)\n\n\n### Solução: out-of-fold predictions\n\n1. Divida os dados em $V$ folds (ex.: 5)\n2. Para cada fold $v$:\n   - Treine cada modelo base nos $V-1$ folds restantes\n   - Faça predição sobre o fold $v$ (dados não vistos)\n3. Use as predições out-of-fold de **todos** os modelos como features para treinar o meta-classificador\n\n\n## Combinando Classificadores (Stacking / Blending)\n\n\n### Combinações comuns\n\n| Tipo | Meta-classificador | Descrição |\n|------|-------------------|-----------|\n| **Blending simples** | Média/votação | Sem meta-modelo, apenas média das probabilidades ou voto majoritário |\n| **Stacking linear** | Regressão logística | Aprende pesos lineares para cada modelo base |\n| **Stacking não-linear** | Árvore/Rede Neural | Aprende interações complexas entre as predições |\n\n\n\n\n## Combinando Classificadores (Stacking / Blending)\n\n<br>\n\n> **Ponto importante:** o stacking funciona melhor quando os modelos base são **diversos**. Nestes casos, cometem erros em padrões diferentes, de modo que o meta-classificador consegue aprender qual modelo é mais confiável em cada situação.\n\n\n\n--- \n\n![](/images/classificacao/stacking.png){fig-align=\"center\"}\n\n\n\n\n## R: Stacking / Blending\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(caret)\nlibrary(ISLR2)\n\nset.seed(335)\n\n# Modelos base com CV\nctrl <- trainControl(method = \"cv\", number = 5,\n                     savePredictions = \"final\",\n                     classProbs = TRUE)\n\nmodelos <- list(\n  logistica = train(default ~ balance + student + income,\n                    data = Default, method = \"glm\", trControl = ctrl),\n  arvore    = train(default ~ balance + student + income,\n                    data = Default, method = \"rpart\", trControl = ctrl),\n  knn       = train(default ~ balance + student + income,\n                    data = Default, method = \"knn\", trControl = ctrl)\n)\n\n# Extrair predicoes out-of-fold para cada modelo\npreds <- data.frame(\n  logistica = modelos$logistica$pred$Yes,\n  arvore    = modelos$arvore$pred$Yes,\n  knn       = modelos$knn$pred$Yes,\n  obs       = modelos$logistica$pred$obs\n)\n\n# Meta-classificador: regressao logistica\nmeta <- train(obs ~ ., data = preds, method = \"glm\",\n              trControl = trainControl(method = \"none\"))\nsummary(meta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nNULL\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -4.36666    0.09314 -46.885   <2e-16 ***\nlogistica    9.52348    0.35288  26.988   <2e-16 ***\narvore      -0.52831    0.79842  -0.662    0.508    \nknn         -0.98458    0.89516  -1.100    0.271    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 2920.6  on 9999  degrees of freedom\nResidual deviance: 1834.4  on 9996  degrees of freedom\nAIC: 1842.4\n\nNumber of Fisher Scoring iterations: 7\n```\n\n\n:::\n:::\n\n\n\n---\n\n### Interpretação do Meta-Classificador (Stacking)\n\nO meta-classificador utiliza as probabilidades preditas pelos modelos base (Regressão Logística, Árvore de Decisão e KNN) como variáveis explicativas.\n\n- O coeficiente da **Regressão Logística** ($\\beta=9.52$, $p<0.001$) é altamente significativo, indicando que suas previsões exercem a maior influência na decisão final do ensemble.<br><br>\n- Os coeficientes da **Árvore de Decisão** ($\\beta=-0.53$, $p=0.508$) e do **KNN** ($\\beta=-0.98$, $p=0.271$) não são estatisticamente significativos, sugerindo contribuição limitada ao meta-modelo.\n\n\n---\n\n### Interpretação do Meta-Classificador (Stacking)\n\n\n- A redução da *Residual Deviance* de **2920.6** para **1834.4** indica melhora substancial no ajuste em relação ao modelo nulo.<br><br>\n- O valor de **AIC = 1842.4** reforça que o modelo apresenta um bom compromisso entre qualidade de ajuste e complexidade.\n\n> **Conclusão:** neste conjunto de dados, o stacking baseia sua decisão principalmente nas previsões da **Regressão Logística**, enquanto Árvore de Decisão e KNN agregam pouca informação adicional ao ensemble.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}